### ISSUE TITLE
Possible ruby error

### ISSUE THREAD

**Issue by srianirudh84** [smaato/puppet-git-hook#2]
I setup this hook script in the server side, and when i push commits to the repo, i get the following error:

git push
Counting objects: 11, done.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 638 bytes, done.
Total 7 (delta 3), reused 0 (delta 0)
remote: manifests/site.pp:
remote: Error: Could not initialize global default settings: couldn't find HOME environment -- expanding `~'
remote:
remote: site.pp:
remote: Error: Could not initialize global default settings: couldn't find HOME environment -- expanding`~'
remote:
remote: Syntax check for puppet manifests failed!

Any insights to this would be helpful!!

I am running my git server on CentOS7 using gitlab

**Comment by Dunedan** [comment]
I had a feeling it relates to the `puppet` command and the `$HOME` environment variable, so I tried out to run puppet with the unset variable:

```
john@foo:/tmp$ unset HOME
john@foo:/tmp$ puppet help
Error: Could not initialize global default settings: couldn't find HOME environment -- expanding `~'
```

As it turns out that's exactly what we originally got as error message.

But why does it need `$HOME` to function. Let's enable some tracing:

```
john@foo:/tmp$ puppet help --trace                                                                                                                                               
Error: Could not initialize global default settings: couldn't find HOME environment -- expanding `~'                                                                                                      
/usr/lib/ruby/vendor_ruby/puppet/util/run_mode.rb:52:in `expand_path'                                                                                                                                     
/usr/lib/ruby/vendor_ruby/puppet/util/run_mode.rb:52:in `which_dir'                                                                                                                                       
/usr/lib/ruby/vendor_ruby/puppet/util/run_mode.rb:58:in `conf_dir'                                                                                                                                        
/usr/lib/ruby/vendor_ruby/puppet/settings.rb:629:in `user_config_file'                                                                                                                                    
/usr/lib/ruby/vendor_ruby/puppet/settings.rb:1079:in `which_configuration_file'                                                                                                                           
/usr/lib/ruby/vendor_ruby/puppet/settings.rb:603:in `parse_config_files'                                                                                                                                  
/usr/lib/ruby/vendor_ruby/puppet/settings.rb:269:in `initialize_global_settings'                                                                                                                          
/usr/lib/ruby/vendor_ruby/puppet.rb:153:in `do_initialize_settings_for_run_mode'                                                                                                                          
/usr/lib/ruby/vendor_ruby/puppet.rb:139:in `initialize_settings'                                                                                                                                          
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:87:in `block in execute'                                                                                                                            
/usr/lib/ruby/vendor_ruby/puppet/util.rb:488:in `exit_on_fail'                                                                                                                                            
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:86:in `execute'
/usr/bin/puppet:8:in `<main>'
```

So apparently the problem appears to be in `puppet/util/run_mode.rb` in line 52. Let's have a look at that part of the [file](https://github.com/puppetlabs/puppet/blob/3.7.2/lib/puppet/util/run_mode.rb#L52):

``` ruby
##
# select the system or the user directory depending on the context of
# this process.  The most common use is determining filesystem path
# values for confdir and vardir.  The intended semantics are:
# {http://projects.puppetlabs.com/issues/16637 #16637} for Puppet 3.x
#
# @todo this code duplicates {Puppet::Settings#which\_configuration\_file}
#   as described in {http://projects.puppetlabs.com/issues/16637 #16637}
def which_dir( system, user )
  File.expand_path(if Puppet.features.root? then system else user end)
end
```

So puppet tries to expand some path. Which and why is described on the page linked in the comments (http://projects.puppetlabs.com/issues/16637):

> Puppet master should default to confdir of ~/.puppet and vardir of ~/.puppet/var when running as non-root, instead defaults to /etc/puppet and /var/lib/puppet respectively.

There we go. Puppet tries to expand the users home directory identified by `~` to know where to find its `confdir` and `vardir` when running as non-root user. Let's try out how that behaves with unset `$HOME`:

```
john@foo:/tmp$ echo $HOME
/home/john
john@foo:/tmp$ irb
irb(main):001:0> File.expand_path('~')
=> "/home/daniel"
irb(main):002:0> exit
john@foo:/tmp$ unset HOME
john@foo:/tmp$ irb
irb(main):001:0> File.expand_path('~')
ArgumentError: couldn't find HOME environment -- expanding `~'
        from (irb):1:in `expand_path'
        from (irb):1
        from /usr/bin/irb:11:in `<main>'

```

So that's it: The expansion of `~` fails, because `$HOME` isn't set.

I played a bit around with the `--confdir` and `--vardir` options of puppet, but wasn't able to get it working with unset `$HOME`.

The possible solutions therefore are:
1. Set `$HOME` for the user running the git hook.
2. Run the git hook as root.

I hope that helps you solving the issue in your environment.

**Comment by srianirudh84** [comment]
Thanks for the response @Dunedan. I will try this recommendation and let you know
